// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {jobs} from '../models';
import {setup} from '../models';

export function Answer(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;

export function CancelJob(arg1:string,arg2:string):Promise<void>;

export function ChooseFolder():Promise<string>;

export function Departments(arg1:string):Promise<Array<config.Department>>;

export function Finish(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ForgetProject(arg1:string):Promise<void>;

export function Jobs(arg1:string):Promise<Array<jobs.Job>>;

export function Projects():Promise<Array<setup.ProjectStatus>>;

export function SaveProject(arg1:setup.ProjectInput):Promise<setup.ProjectStatus>;

export function SendMessage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ShowInFinder(arg1:string):Promise<void>;

export function StartJob(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function Thread(arg1:string,arg2:string):Promise<Array<jobs.Entry>>;
