// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Answer(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Answer'](arg1, arg2, arg3, arg4);
}

export function CancelJob(arg1, arg2) {
  return window['go']['main']['App']['CancelJob'](arg1, arg2);
}

export function ChooseFolder() {
  return window['go']['main']['App']['ChooseFolder']();
}

export function Departments(arg1) {
  return window['go']['main']['App']['Departments'](arg1);
}

export function Finish(arg1, arg2, arg3) {
  return window['go']['main']['App']['Finish'](arg1, arg2, arg3);
}

export function ForgetProject(arg1) {
  return window['go']['main']['App']['ForgetProject'](arg1);
}

export function Jobs(arg1) {
  return window['go']['main']['App']['Jobs'](arg1);
}

export function OpenPulls(arg1, arg2) {
  return window['go']['main']['App']['OpenPulls'](arg1, arg2);
}

export function Projects() {
  return window['go']['main']['App']['Projects']();
}

export function ReviewComments(arg1, arg2) {
  return window['go']['main']['App']['ReviewComments'](arg1, arg2);
}

export function SaveProject(arg1) {
  return window['go']['main']['App']['SaveProject'](arg1);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3);
}

export function ShowInFinder(arg1) {
  return window['go']['main']['App']['ShowInFinder'](arg1);
}

export function StartJob(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartJob'](arg1, arg2, arg3, arg4);
}

export function Thread(arg1, arg2) {
  return window['go']['main']['App']['Thread'](arg1, arg2);
}
